<?php

namespace Container1GuXpC7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormationRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Y5zq2EU.app\Repository\FormationRepository' shared service.
     *
     * @return \app\Repository\FormationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Y5zq2EU": it references class "app\\Repository\\FormationRepository" but no such service exists. Did you mean "App\\Repository\\FormationRepository"?');
    }
}
