<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1GuXpC7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1GuXpC7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1GuXpC7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1GuXpC7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1GuXpC7\App_KernelDevDebugContainer([
    'container.build_hash' => '1GuXpC7',
    'container.build_id' => 'aca6343e',
    'container.build_time' => 1718348782,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1GuXpC7');
